
FROM oraclelinux:7-slim

ENV LIVY_VERSION="0.8.0-incubating_2.12"
ENV LIVY_HOME="/opt/livy"

ADD jdk-17.0.14_linux-x64_bin.rpm /tmp
RUN yum update -y && \
    yum install -y vi curl unzip procps ca-certificates && \
    yum -y localinstall /tmp/jdk-17.0.14_linux-x64_bin.rpm && \
    yum -y clean all && \
    rm  -rf /var/cache/yum

RUN curl https://downloads.apache.org/incubator/livy/${LIVY_VERSION}-incubating/apache-livy-${LIVY_VERSION}-incubating_2.12-bin.zip -o /tmp/apache-livy-${LIVY_VERSION}-bin.zip && \
        unzip /tmp/apache-livy-${LIVY_VERSION}-bin.zip -d /opt && \
        mv /opt/apache-livy-${LIVY_VERSION}-bin /opt/livy && \
        mkdir -p ${LIVY_HOME}/logs && \
        rm /tmp/apache-livy-${LIVY_VERSION}-bin.zip
    
ENV PATH="/opt/livy/bin:${PATH}"

EXPOSE 8998

ENTRYPOINT ["tail", "-f", "/dev/null"]


